---
name: ConsumableCooldowns
version: 1.0.0
main: Mencoreh\ConsumableCooldowns\Main
api: 5.13.0
src-namespace-prefix: Mencoreh\ConsumableCooldowns
permissions:
  consumablecooldowns.bypass:
    description: "Bypass the cooldowns of the consumable items."
    default: op
...
